### ISSUE TITLE
环境配置问题

### ISSUE THREAD

**Issue by YangYuchi11** [wyn430/MVGCN#1]
王教授，您好，在复现您的代码的时候，我在安装torch1.4的时候，由于版本太过老旧，遇到了很多问题，torch1.4对应的cuda好像没有11版本的，请问您有训练好的模型没有，我想直接用来测试下我的数据集。谢谢

**Comment by wyn430** [comment]
> 王教授，您好，在复现您的代码的时候，我在安装torch1.4的时候，由于版本太过老旧，遇到了很多问题，torch1.4对应的cuda好像没有11版本的，请问您有训练好的模型没有，我想直接用来测试下我的数据集。谢谢

The code has been tested on the latest torch. Please find the updated environment in the repo.
The pre-trained model is also uploaded.

**Comment by YangYuchi11** [comment]
好的 非常谢谢您的帮助！

**Comment by YangYuchi11** [comment]
王教授，您好！我试了一下 加载 您的那个t7文件。那个好像只有参数信息 没有网络结构 请问那个分别用的是什么网络结构。如果可以的您可不可以提供测试和可视化的代码呢，我只需要更改输入的数据就可以的那种。还有请问下您的pcd文件包含的是哪些数据信息，xyz 法向量 ？非常抱歉再次打扰您，我是真的想向您学习这个方法。
