### ISSUE TITLE
How do you deploy trained models

### ISSUE THREAD

**Issue by wjiangsheng** [wyn430/MVGCN#2]
Hello, I would like to ask how to apply this trained model to data prediction, I have tried several times but failed

**Comment by wyn430** [comment]
> Hello, I would like to ask how to apply this trained model to data prediction, I have tried several times but failed

The trained model is saved in ".t7" file, which is the model weights. The model architecture needs to be first built and then the model weights need to be loaded by using "model.load_state_dict(torch.load('filename.t7'))".
